config/routes.rb
Rails.application.routes.draw do
  root 'appointments#index'
  resources :appointments
  resources :doctors
  match 'hospitals', to: 'doctors#hospitals', via: :get
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer class="navbar fixed-bottom">
  <div class="container">
    Be Free <%= Time.now.year %>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="https://still-mountain-95524.herokuapp.com/">Be Free App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
          
        <li class="nav-item active">
           <%= link_to "My Appointments", '/', :class => 'nav-link'  %> 
        </li>
        <li class="nav-item">
           <%= link_to "Book Appointment", new_appointment_path, :class => 'nav-link'  %> 
        </li>
         <li class="nav-item">
           <%= link_to "Nearby Doctors", hospitals_path, :class => 'nav-link'  %> 
        </li>
    </ul>
         <span class="navbar-text">
        <ul class="navbar-nav mr-auto">
           <li class="nav-item">
         <%= link_to "Discussions", 'https://enigmatic-atoll-65882.herokuapp.com/',  :class => 'nav-link' %>
        </li>
         <li class="nav-item">
          <%= link_to "Payments", 'https://secure-cliffs-28598.herokuapp.com/', :class => 'navbar-link', :class => 'nav-link'%>
        </li> 
    </ul>
        </span>     
  </div>
</nav>