config/routes.rb
Rails.application.routes.draw do
  root 'appointments#index'
  resources :appointments
  resources :doctors
  match 'hospitals', to: 'doctors#hospitals', via: :get
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: appointments
#
#  id          :bigint           not null, primary key
#  title       :string
#  user_id     :bigint           not null
#  start_date  :datetime
#  end_date    :datetime
#  doctor_name :string
#
class Appointment < ApplicationRecord
  belongs_to :user, optional: true
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

require 'google/apis/calendar_v3'
require 'google/api_client/client_secrets.rb'

class AppointmentsController < ApplicationController
  CALENDAR_ID = 'primary'
  before_action :set_appointment, only: %i[show edit update destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.where(user: @user)
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show; end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit; end

  # POST /appointments
  # POST /appointments.json
  def create
     if @user&.refresh_token.present?
      client = get_google_calendar_client @user
      appointment = params[:appointment]
      event = get_event appointment
      client.insert_event('primary', event)
      flash[:notice] = 'Appointment successfully created'
      @user.appointments.create(appointment_params)
      redirect_to appointments_path
    else
     
      none_gmail_users
    end
  end

  def get_google_calendar_client(user)
    client = Google::Apis::CalendarV3::CalendarService.new
    secrets = Google::APIClient::ClientSecrets.new({
                                                     'web' => {
                                                       'access_token' => user&.access_token,
                                                       'refresh_token' => user&.refresh_token,
                                                       'client_id' => ENV['CALENDAR_CLIENT_ID'],
                                                       'client_secret' => ENV['CALENDAR_CLIENT_SECRET']
                                                     }
                                                   })
    begin client.authorization = secrets.to_authorization
          client.authorization.grant_type = 'refresh_token'

          unless user.present?
            client.authorization.refresh_token
            user.update_attributes(
              access_token: client.authorization.access_token,
              refresh_token: client.authorization.refresh_token,
              expires_at: client.authorization.expires_at.to_i
            )
          end
    rescue StandardError => e
      flash[:error] = 'Your token has expired. please relogin with Google'
      redirect_to :back
    end
    client
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_appointment
    @appointment = Appointment.find_by_id(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def appointment_params
    params.require(:appointment).permit(:title, :user_id, :description, :start_date, :end_date, :doctor_name)
  end

  def none_gmail_users
    @appointment = @user.appointments.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_event(app)
    app = Google::Apis::CalendarV3::Event.new({
                                               summary: app[:title],
                                               location: request.location,
                                               description: app[:description],
                                               start: {
                                                 date_time: Time.new(app['start_date(1i)'],app['start_date(2i)'],app['start_date(3i)'],app['start_date(4i)'],app['start_date(5i)']).to_datetime.rfc3339,
                                                 time_zone: "Africa/Johannesburg"

                                               },
                                               end: {
                                                 date_time: Time.new(app['end_date(1i)'],app['end_date(2i)'],app['end_date(3i)'],app['end_date(4i)'],app['end_date(5i)']).to_datetime.rfc3339,
                                                 time_zone: "Africa/Johannesburg"
                                               },
                                               
                                               reminders: {
                                                 use_default: false,
                                                 overrides: [
                                                   Google::Apis::CalendarV3::EventReminder.new(reminder_method: 'popup', minutes: 10),
                                                   Google::Apis::CalendarV3::EventReminder.new(reminder_method: 'email', minutes: 1440),
                                                   Google::Apis::CalendarV3::EventReminder.new(reminder_method: 'email', minutes: 30)

                                                 ]
                                               },
                                               notification_settings: {
                                                 notifications: [
                                                   { type: 'event_creation', method: 'email' },
                                                   { type: 'event_change', method: 'email' },
                                                   { type: 'event_cancelation', method: 'email' },
                                                   { type: 'event_response', method: 'email' }
                                                 ]
                                               }, 'primary': true

                                             })
  end
end

app/views/appointments/_form.html.erb
<div class='form-group'>
    <div class="col-md-8">
      <%= form_with(model: appointment, local: true) do |form| %>
        <% if appointment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

            <ul>
              <% appointment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :title, for: "exampleFormControlInput1" %>
          <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :start_date, for: "exampleFormControlInput1" %>
          <%= form.datetime_select :start_date, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= form.label :end_date, for: "exampleFormControlInput1" %>
          <%= form.datetime_select :end_date, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :doctor_name,for: "exampleFormControlInput1" %>
          <%= form.text_field :doctor_name, class: "form-control" %>
        </div>


        <div class="form-group">
          <%= form.label :description, for: "exampleFormControlInput1" %>
          <%= form.text_area :description, class: "form-control"%>
        </div>

        <div class="actions">
          <%= form.submit 'Submit', class: "btn btn-primary lg" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>
<h1>My Appointments</h1>
<div class="list-group">
<div class="overflow-auto">
  
  <% @appointments&.each do |app| %>
   <div class="forum-item">
      <%= link_to app, class: "list-group-item list-group-item-action" do %>
        <div class="d-flex w-100 justify-content-between ">
          <h5 class="mb-1"><b><%= app&.title %></b></h5>
          <small><b></b>From: <%= app&.start_date %></small>
        </div>
        <p class="mb-1"><%= app&.description %></p>
        <small><b>By Doctor: </b><%= app&.doctor_name %></small>            
      <% end %>
    </div>
    <% end %>

  </div>
</div>
<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h4>Book a new appointment with your appointment</h4>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @appointment&.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted">With Dr.: <%= @appointment&.doctor_name %></h6>
    <p class="card-text"><strong><p>Start Time</strong></p><p><%= @appointment&.start_date %></p>
    <p class="card-text"> <strong><p>End Time</strong></p><p><%= @appointment&.end_date %></p>
    <p class="card-text"><%= @appointment&.description %></p>
    <a href="#" class="card-link"><%= link_to 'Edit', edit_appointment_path(@appointment) %></a> |
    <a href="#" class="card-link"><%= link_to 'Back', appointments_path %></a>
  </div>
</div>